// Central config for every content module. The generic ModulePage component
// reads this to render the right table columns + add/edit form fields,
// and talks to the matching backend controller (endpoint).
//
// field.type: text | textarea | number | date | checkbox | file
// field.image: true -> shows an image preview + counts as the "thumb" column

export const modules = {
  about: {
    key: 'about',
    label: 'About',
    icon: 'bi-info-circle',
    color: '#2f6fed',
    endpoint: '/about',
    titleField: 'title',
    imageField: 'imagePath',
    fields: [
      { name: 'title', label: 'Title', type: 'text', full: true ,required: false},
      { name: 'description', label: 'Description', type: 'textarea', full: true },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'showOnHomePage', label: 'Home Page', type: 'checkbox', group: 'Show On Website' },
      { name: 'showOnAboutPage', label: 'About Page', type: 'checkbox', group: 'Show On Website', default: true },
      { name: 'showOnFooter', label: 'Footer', type: 'checkbox', group: 'Show On Website' },
      { name: 'isDirectorMessage', label: 'Use this entry on Director Message page', type: 'checkbox', default: false, full: true },
      { name: 'image', label: 'Image', type: 'file', image: true, hint: 'Recommended size: 1200x600' },
    ],
    columns: [
      { key: 'thumb', label: 'Image' },
      { key: 'title', label: 'Title' },
      { key: 'displayOrder', label: 'Order' },
      { key: 'status', label: 'Status' },
      { key: 'showOn', label: 'Show On' },
    ],
  },

  faculty: {
    key: 'faculty',
    label: 'Faculty',
    icon: 'bi-people',
    color: '#16a34a',
    endpoint: '/faculty',
    titleField: 'name',
    imageField: 'photoPath',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'designation', label: 'Designation', type: 'text' },
      { name: 'qualification', label: 'Qualification', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'bio', label: 'Bio', type: 'textarea', full: true },
      { name: 'isGuestFaculty', label: 'Guest Faculty (show on Guest Faculty page)', type: 'checkbox', default: false, full: true },
      { name: 'isDirector', label: 'Director (hide from Faculty page)', type: 'checkbox', default: false, full: true },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'photo', label: 'Photo', type: 'file', image: true },
    ],
    columns: [
      { key: 'thumb', label: 'Photo' },
      { key: 'name', label: 'Name' },
      { key: 'designation', label: 'Designation' },
      { key: 'displayOrder', label: 'Order' },
      { key: 'status', label: 'Status' },
    ],
  },

  staff: {
    key: 'staff',
    label: 'Staff',
    icon: 'bi-person-badge',
    color: '#f59e0b',
    endpoint: '/staff',
    titleField: 'name',
    imageField: 'photoPath',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'designation', label: 'Designation', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'photo', label: 'Photo', type: 'file', image: true },
    ],
    columns: [
      { key: 'thumb', label: 'Photo' },
      { key: 'name', label: 'Name' },
      { key: 'designation', label: 'Designation' },
      { key: 'displayOrder', label: 'Order' },
      { key: 'status', label: 'Status' },
    ],
  },

  gallery: {
    key: 'gallery',
    label: 'Gallery',
    icon: 'bi-image',
    color: '#8b5cf6',
    endpoint: '/gallery',
    titleField: 'title',
    imageField: 'imagePath',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'text', required: true, hint: 'Use the same category name for all photographs in one album.' },
      { name: 'isPrimary', label: 'Category cover image (shown on Home)', type: 'checkbox', default: false, full: true },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'images', label: 'Photos', type: 'file', image: true, multiple: true, requiredOnCreate: true, hint: 'Select one or more photos. The first photo is used as the cover when “Category cover image” is checked.' },
    ],
    columns: [
      { key: 'thumb', label: 'Image' },
      { key: 'title', label: 'Title' },
      { key: 'category', label: 'Category' },
      { key: 'displayOrder', label: 'Order' },
      { key: 'status', label: 'Status' },
    ],
  },

  news: {
    key: 'news',
    label: 'News',
    icon: 'bi-newspaper',
    color: '#ef4444',
    endpoint: '/news',
    titleField: 'title',
    imageField: 'imagePath',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, full: true },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
      { name: 'linkUrl', label: 'News link (optional)', type: 'text', full: true, hint: 'Internal path, e.g. /notices, or a complete https:// link.' },
      { name: 'publishDate', label: 'Publish Date', type: 'date', default: 'today' },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'image', label: 'Image', type: 'file', image: true },
    ],
    columns: [
      { key: 'thumb', label: 'Image' },
      { key: 'title', label: 'Title' },
      { key: 'publishDate', label: 'Publish Date', date: true },
      { key: 'displayOrder', label: 'Order' },
      { key: 'status', label: 'Status' },
    ],
  },

  events: {
    key: 'events',
    label: 'Events',
    icon: 'bi-calendar-event',
    color: '#06b6d4',
    endpoint: '/events',
    titleField: 'title',
    imageField: 'imagePath',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, full: true },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
      { name: 'eventDate', label: 'Event Date', type: 'date', default: 'today' },
      { name: 'venue', label: 'Venue', type: 'text' },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'image', label: 'Image', type: 'file', image: true },
    ],
    columns: [
      { key: 'thumb', label: 'Image' },
      { key: 'title', label: 'Title' },
      { key: 'eventDate', label: 'Event Date', date: true },
      { key: 'venue', label: 'Venue' },
      { key: 'status', label: 'Status' },
    ],
  },

  notice: {
    key: 'notice',
    label: 'Notice',
    icon: 'bi-megaphone',
    color: '#ec4899',
    endpoint: '/notice',
    titleField: 'title',
    imageField: null,
    fileField: 'filePath',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, full: true },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
      { name: 'noticeDate', label: 'Notice Date', type: 'date', default: 'today' },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'file', label: 'Attachment (PDF)', type: 'file', hint: 'PDF, DOC allowed' },
    ],
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'noticeDate', label: 'Notice Date', date: true },
      { key: 'file', label: 'File' },
      { key: 'status', label: 'Status' },
    ],
  },

  slider: {
    key: 'slider',
    label: 'Slider',
    icon: 'bi-images',
    color: '#f59e0b',
    endpoint: '/slider',
    titleField: 'title',
    imageField: 'imagePath',
    fields: [
      { name: 'title', label: 'Title', type: 'text' },
      { name: 'linkUrl', label: 'Link URL', type: 'text' },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'image', label: 'Slide Image', type: 'file', image: true, requiredOnCreate: true, hint: 'Recommended size: 1920x700' },
    ],
    columns: [
      { key: 'thumb', label: 'Image' },
      { key: 'title', label: 'Title' },
      { key: 'displayOrder', label: 'Order' },
      { key: 'status', label: 'Status' },
    ],
  },

  courses: {
    key: 'courses',
    label: 'Courses',
    icon: 'bi-mortarboard',
    color: '#111827',
    endpoint: '/courses',
    titleField: 'name',
    imageField: 'imagePath',
    fileField: 'pdfPath',
    fields: [
      { name: 'name', label: 'Course Name', type: 'text', required: true, full: true },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
      { name: 'duration', label: 'Duration', type: 'text' },
      { name: 'eligibility', label: 'Eligibility', type: 'text' },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'image', label: 'Course Cover Image (JPG/PNG)', type: 'file', image: true, accept: 'image/jpeg,image/png,image/webp', hint: 'Recommended cover size: 1200x700 px' },
      { name: 'pdf', label: 'Course PDF / Syllabus', type: 'file', accept: 'application/pdf', hint: 'PDF only — syllabus, brochure or ordinance.' },
    ],
    columns: [
      { key: 'thumb', label: 'Image' },
      { key: 'name', label: 'Course' },
      { key: 'duration', label: 'Duration' },
      { key: 'file', label: 'PDF' },
      { key: 'status', label: 'Status' },
    ],
  },

  downloads: {
    key: 'downloads',
    label: 'Downloads',
    icon: 'bi-download',
    color: '#0d9488',
    endpoint: '/downloads',
    titleField: 'title',
    imageField: null,
    fileField: 'filePath',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, full: true },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'file', label: 'File', type: 'file', requiredOnCreate: true },
    ],
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'category', label: 'Category' },
      { key: 'file', label: 'File' },
      { key: 'status', label: 'Status' },
    ],
  },

  publications: {
    key: 'publications',
    label: 'Publications',
    icon: 'bi-journal-text',
    color: '#065f46',
    endpoint: '/publications',
    titleField: 'title',
    imageField: null,
    fileField: 'filePath',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, full: true },
      { name: 'author', label: 'Author', type: 'text' },
      { name: 'publishYear', label: 'Publish Year', type: 'number' },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'file', label: 'File', type: 'file' },
    ],
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'author', label: 'Author' },
      { key: 'publishYear', label: 'Year' },
      { key: 'status', label: 'Status' },
    ],
  },

  navigation: {
    key: 'navigation',
    label: 'Navigation Menu',
    icon: 'bi-list',
    color: '#6366f1',
    endpoint: '/navigation',
    titleField: 'label',
    imageField: null,
    fields: [
      { name: 'label', label: 'Label', type: 'text', required: true },
      { name: 'url', label: 'URL', type: 'text', full: true, hint: 'Internal path (e.g. /about) or full https:// URL' },
      { name: 'parentId', label: 'Parent Menu Item', type: 'number', hint: 'Leave empty for top-level menu items' },
      { name: 'iconKey', label: 'Icon Key', type: 'text', hint: 'Bootstrap icon name (e.g. bi-house, bi-book)' },
      { name: 'isExternal', label: 'External Link', type: 'checkbox', default: false, full: true },
      { name: 'openInNewTab', label: 'Open in New Tab', type: 'checkbox', default: false, full: true },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
    ],
    columns: [
      { key: 'label', label: 'Label' },
      { key: 'url', label: 'URL' },
      { key: 'parentId', label: 'Parent' },
      { key: 'displayOrder', label: 'Order' },
      { key: 'status', label: 'Status' },
    ],
  },

  footerlinks: {
    key: 'footerlinks',
    label: 'Footer Links',
    icon: 'bi-link-45deg',
    color: '#8b5cf6',
    endpoint: '/footerlinks',
    titleField: 'label',
    imageField: null,
    fields: [
      { name: 'label', label: 'Label', type: 'text', required: true },
      { name: 'url', label: 'URL', type: 'text', full: true, hint: 'Internal path (e.g. /about) or full https:// URL' },
      { name: 'section', label: 'Section', type: 'text', required: true, hint: 'Section name: Quick Links, Important Links, Student Corner, Follow Us' },
      { name: 'isExternal', label: 'External Link', type: 'checkbox', default: false, full: true },
      { name: 'openInNewTab', label: 'Open in New Tab', type: 'checkbox', default: false, full: true },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
    ],
    columns: [
      { key: 'label', label: 'Label' },
      { key: 'url', label: 'URL' },
      { key: 'section', label: 'Section' },
      { key: 'displayOrder', label: 'Order' },
      { key: 'status', label: 'Status' },
    ],
  },

  facilities: {
    key: 'facilities',
    label: 'Infrastructure / Facilities',
    icon: 'bi-building',
    color: '#0d9488',
    endpoint: '/facilities',
    titleField: 'name',
    imageField: 'imagePath',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
      { name: 'iconKey', label: 'Icon Key', type: 'text', hint: 'Bootstrap icon name (e.g. bi-pc-display, bi-book)' },
      { name: 'displayOrder', label: 'Display Order', type: 'number', default: 1 },
      { name: 'isActive', label: 'Active', type: 'checkbox', default: true },
      { name: 'image', label: 'Image', type: 'file', image: true, hint: 'Recommended size: 800x600' },
    ],
    columns: [
      { key: 'thumb', label: 'Image' },
      { key: 'name', label: 'Name' },
      { key: 'displayOrder', label: 'Order' },
      { key: 'status', label: 'Status' },
    ],
  },
};

export const moduleList = Object.values(modules);
